### ISSUE TITLE
Xcode 8 Hangs after opening Storyboard

### ISSUE THREAD

**Issue by miraz029** [AdColony/AdColony-iOS-SDK-3#10]
I added AdColony-iOS-SDK-3 in a Swift3 project with CocoaPods and also shown interstitial ads successfully (no warning). But if I open storyboard, Xcode hangs and not responding. 

If I just remove AdColony sdk, Storyboard is working again just fine. Its very weird. Do I need to add developers account to use the SDK? Is there any other issues?

**Comment by cmanibog-ac** [comment]
We have not yet heard of this issue. If you are still experiencing this issue with Storyboard, please  open a ticket with our support team by sending an e-mail to support@adcolony.com
