### ISSUE TITLE
Crashes  ADCWebViewModule with WebView

### ISSUE THREAD

**Issue by AssassinSC** [AdColony/AdColony-iOS-SDK-3#13]
#41. Crashed: AdColony Worker
0  libobjc.A.dylib                0x18fb46f30 objc_msgSend + 16
1  CoreFoundation                 0x190fd2350 CFBasicHashAddValue + 204
2  CoreFoundation                 0x190fe7888 CFRunLoopAddTimer + 488
3  JavaScriptCore                 0x195870fe4 WTF::RunLoop::TimerBase::start(double, bool) + 188
4  WebKit                         0x19a4e76f8 WebKit::ProcessThrottler::updateAssertion() + 380
5  WebKit                         0x19a492e60 WTF::RefCounter<WebKit::ProcessThrottler::BackgroundActivityCounterType>::Count::deref() + 64
6  WebKit                         0x19a6135f4 WebKit::WebProcessProxy::didSetAssertionState(WebKit::AssertionState) + 700
7  WebKit                         0x19a4e7558 WebKit::ProcessThrottler::updateAssertionNow() + 380
8  WebKit                         0x19a492e14 WTF::RefCounter<WebKit::ProcessThrottler::BackgroundActivityCounterType>::Count::ref() + 60
9  WebKit                         0x19a5b2a0c WebKit::WebPageProxy::runJavaScriptInMainFrame(WTF::String const&, std::__1::function<void (API::SerializedScriptValue*, bool, WebCore::ExceptionDetails const&, WebKit::CallbackBase::Error)>) + 284
10 WebKit                         0x19a69d5c8 -[WKWebView evaluateJavaScript:completionHandler:] + 152
11 ##############                 0x1013458b0 -[ADCWebViewModule pumpMessages:] (ADCWebViewModule.m:458)
12 ##############                 0x10134f0a8 -[ADCNativeLayer update] (ADCNativeLayer.m:192)
13 Foundation                     0x191be48f8 __NSFireTimer + 88
14 CoreFoundation                 0x1910a88f4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
15 CoreFoundation                 0x1910a8608 __CFRunLoopDoTimer + 872
16 CoreFoundation                 0x1910a7ec4 __CFRunLoopDoTimers + 244
17 CoreFoundation                 0x1910a5ac0 __CFRunLoopRun + 1572
18 CoreFoundation                 0x190fd4048 CFRunLoopRunSpecific + 444
19 Foundation                     0x191ae5a8c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
20 ##############                 0x10139d9dc -[AdColony setupWorkerThread] (AdColony.m:117)
21 Foundation                     0x191be347c __NSThread__start__ + 1024
22 libsystem_pthread.dylib        0x190190850 _pthread_body + 240
23 libsystem_pthread.dylib        0x190190760 _pthread_body + 282
24 libsystem_pthread.dylib        0x19018ddac thread_start + 4

**Comment by cmanibog-ac** [comment]
This has been fixed in v3.0.6.
