### ISSUE TITLE
Crash on JSON serialisation

### ISSUE THREAD

**Issue by staskochkin** [AdColony/AdColony-iOS-SDK-3#16]
After installation AdColony-iOS-SDK 3.0.6 occurred this crash in  AdColony Worker thread.

Thread 54 name:  AdColony Worker
Thread 54 Crashed:
0   Foundation                    	0x0000000184f25ca8 _convertJSONString + 296
1   Foundation                    	0x0000000184f25c7c _convertJSONString + 252
2   Foundation                    	0x0000000184f25100 _writeJSONString + 124
3   Foundation                    	0x0000000184f23d38 _writeJSONValue + 116
4   Foundation                    	0x0000000184f260d8 ___writeJSONObject_block_invoke + 236
5   CoreFoundation                	0x00000001842cf548 __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 88
6   CoreFoundation                	0x00000001842bd3fc -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 224
7   Foundation                    	0x0000000184f25864 _writeJSONObject + 340
8   Foundation                    	0x0000000184f23e4c _writeJSONValue + 392
9   Foundation                    	0x0000000184f262c0 ___writeJSONArray_block_invoke + 144
10  CoreFoundation                	0x0000000184275414 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 132
11  CoreFoundation                	0x0000000184275280 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 168
12  Foundation                    	0x0000000184f25abc _writeJSONArray + 296
13  Foundation                    	0x0000000184f23eec _writeJSONValue + 552
14  Foundation                    	0x0000000184f23c7c -[_NSJSONWriter dataWithRootObject:options:error:] + 140
15  Foundation                    	0x0000000184f24cc0 +[NSJSONSerialization dataWithJSONObject:options:error:] + 348
16  11testads                     	0x0000000101307808 +[ADCMessage stringFromMessages:] (ADCMessage.m:152)
17  11testads                     	0x00000001012e4bf0 -[ADCJSCoreModule pumpMessages:] (ADCJSCoreModule.m:126)
18  11testads                     	0x000000010130e910 -[ADCNativeLayer update] (ADCNativeLayer.m:192)
19  Foundation                    	0x0000000184e9e2e4 __NSFireTimer + 88
20  CoreFoundation                	0x00000001843371d8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
21  CoreFoundation                	0x0000000184336eec __CFRunLoopDoTimer + 872
22  CoreFoundation                	0x00000001843367a8 __CFRunLoopDoTimers + 244
23  CoreFoundation                	0x00000001843343a4 __CFRunLoopRun + 1572
24  CoreFoundation                	0x00000001842622b8 CFRunLoopRunSpecific + 444
25  Foundation                    	0x0000000184d9f26c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
26  11testads                     	0x000000010135d244 -[AdColony setupWorkerThread] (AdColony.m:117)
27  Foundation                    	0x0000000184e9ce68 __NSThread__start__ + 1024
28  libsystem_pthread.dylib       	0x000000018341d850 _pthread_body + 240
29  libsystem_pthread.dylib       	0x000000018341d760 _pthread_body + 0
30  libsystem_pthread.dylib       	0x000000018341ad94 thread_start + 4

It's not look like that integration problem because you use +[NSJSONSerialization dataWithJSONObject:options:error:]  method that is unsafe and can raise exceptions if JSON object is not valid.

**Comment by lobovkin** [comment]
See more crushes on Analytics for last few days. 3.0.6 SDK.

**Comment by cmanibog-ac** [comment]
To troubleshoot this further, please send a Charles log or a full console log showing the app activity from when our SDK is initialized through the crash. These crash logs are similar to crashes seen in our 3.0.4 SDK and should have been fixed in 3.0.6. That said, our Engineering team has re-opened this bug and can investigate further once we have the additional logs.

**Comment by staskochkin** [comment]
@cmanibog-ac  I catch this exception from Analytics, and haven't Charles/XCode logs. On internal testing stage we can't reproduce this behaviour.

**Comment by cmanibog-ac** [comment]
Could you send a link to your Crashlytics tracking? This will provide us a bit more information for troubleshooting. You can also send this link directly to our Support team by sending a message to support@adcolony.com.

**Comment by lobovkin** [comment]
Hello. Any updates? See more crushes for 2 apps with new SDK 3.0.6 and normal with previous SDK 2.

**Comment by cmanibog-ac** [comment]
This is fixed in our 3.1 update.
