### ISSUE TITLE
AdColony [*** ERROR ***] : Tried to show an expired interstitial ad.

### ISSUE THREAD

**Issue by yomanx** [AdColony/AdColony-iOS-SDK-3#17]
why??? 

my game freezing.....

**Comment by mwhite-ac** [comment]
Thank you for reaching out, this is not a question that we can help with in this format as we need more information.  I need you to send a full console log to our Support Team, this log should show all app activity from when you initialize our SDK through a video view and the freeze event that you're seeing.  Include what version of our SDK you're working with and what platform your app is on and a description of the freeze and the step to reproduce it.  

Our Support Team's email is support@adcolony.com.
