### ISSUE TITLE
2.x podspec pointing to non-existent repo

### ISSUE THREAD

**Issue by leamerluck** [AdColony/AdColony-iOS-SDK-3#18]
I have a project that was using AdColony 2.6.2. It was building fine locally but when trying to install on another machine CocoaPod install is failing with the error: `'fatal: repository 'https://github.com/AdColony/AdColony-iOS-SDK.git/' not found`

I figured I'd open an issue so that others were aware what the problem was. An SDK update to 3.1 is the only solution, I assume, since that repo is no longer available for 2.x. 

Also, the AdColony QuickStart setup is not accurate (at least the rewarded interstitials).

**Comment by zeevvax** [comment]
We have the same issue, waiting to hear from AdColony. In the meantime I added the framework directly by changing the Podfile (or in my case the pod spec) as follow 
#offers.dependency 'AdColony', '2.6.3'
    s.vendored_frameworks  = 'AdColony/AdColony.framework'
    s.weak_frameworks = 'AdSupport', 'AudioToolbox', 'AVFoundation', 'CoreTelephony', 'EventKit','JavaScriptCore','MessageUI','Social','StoreKit','SystemConfiguration','WatchConnectivity','WebKit'

**Comment by cmanibog-ac** [comment]
Apologies for the delay. We have removed our 2.x repo in preparation of sunsetting support for these SDK versions later this year and having publishers integrate with our updated 3.x API moving forward.

**Comment by piyushg91** [comment]
That's pretty shady behavior. You guys basically pulled the rug out from under everyone's feet. 

@leamerluck , I was able to find someone else's fork: 
https://github.com/javis007/AdColony-iOS-SDK/commits/master

You'll have to change your AdColony to point to this.
