### ISSUE TITLE
No way to check a zone's ability to show an ad before actually attempting to show it

### ISSUE THREAD

**Issue by ekilah** [AdColony/AdColony-iOS-SDK-3#19]
The method used to show an AdColony interstitial returns a `BOOL` like so:

```/**
 @abstract Triggers a fullscreen ad experience.
 @param viewController The view controller on which the interstitial will display itself.
 @return Whether the ad was able to start playback.
 */
- (BOOL)showWithPresentingViewController:(UIViewController *)viewController;
```

However, there is no way to query whether or not the ad will be able to start playback or not, and there is no list of reasons provided to describe why the return value here would ever be `NO`.

We've noticed that this method will return `NO` in at least one case that should be predictable, and therefore should be added as an extra API that we can query. Here's a log message that is printed when two ads are played back-to-back:

> AdColony [Info] : Tried to play an ad, but we are skipping this request because of the zone's interval setting

Can you add a method, similar to the `expired` boolean property, so we can check for this condition prior to actually trying to show the ad? And, can you enumerate the possible other reasons the call to show the ad might fail in the header (also considering which of those other possibilities might be good as new API to query)?

**Comment by cmanibog-ac** [comment]
Ad availability can be checked before the show call with the requestInterstitial method. This will pass to either the success or failure block, which can then be used to control the availability of your watch button. For further discussion and to see its implementation, I recommend reviewing our sample app at https://github.com/AdColony/AdColony-iOS-SDK-3/blob/master/SampleApps/ObjC/AdColonyBasic/AdColonyBasic/ViewController.m. If there are additional questions, please submit a ticket directly to our Support team at support@adcolony.com

**Comment by ekilah** [comment]
Well, it's either a bug or a feature, but this condition is not covered by the `failure` block in 3.1.0 and 3.1.1. The success callback is called in this scenario.
