### ISSUE TITLE
AdColonyZone reward block not called

### ISSUE THREAD

**Issue by dwxw** [AdColony/AdColony-iOS-SDK-3#2]
I'm migrating to the new SDK.  For my rewarded ad the zone.reward block is never called.  The zone type is Preroll/Interstitial if that makes a difference.  I'm only interested if the ad was watched to completion.  How can I do this with the new SDK?

**Comment by pangia** [comment]
AdColony, please comment on this and other issues reported with SDK 3.0

**Comment by owainm** [comment]
Your zone type needs to be set to 'Value Exchange/V4VC'. Please refer to our [documentation](https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Rewarded-Interstitial-Ads-Quick-Start-Guide)  for details.
