### ISSUE TITLE
Adcoloany version 3.0.4.1 after showing ads VC is not dismissing.

### ISSUE THREAD

**Issue by anil03** [AdColony/AdColony-iOS-SDK-3#22]
I am using Adcolony 3.0.4.1 which available in CocoaPods. I updated the pods file.

: AdColony controller version: 1.0.5.11

It is launching ads after finishing video it is showing BLACK screen. I can not go back to my view controller file.

NOTE: It run sample app it is working fine. with manual installation

Please update cocoa pods file in GITHUB with latest version.

**Comment by cmanibog-ac** [comment]
The pod file should be updated with our latest SDK, v3.1.1. Could I have you install this version and test again? If you are still seeing the black screen issue after updating, please send a console log showing the app activity from when our SDK is initialized through the black screen issue to our support team at support@adcolony.com.

**Comment by anil03** [comment]
just updated the Pods file and it worked.
thanks for reply.
