### ISSUE TITLE
Problem with  AdColonyAdapter.framework

### ISSUE THREAD

**Issue by tigrim** [AdColony/AdColony-iOS-SDK-3#23]
I have problem with  with  AdColonyAdapter.framework. Add in project AdColonyAdapter-3.1.1 and AdColony-iOS-SDK-3-3.1.1. I got next errors

**Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AdColonyAppOptions", referenced from:
      objc-class-ref in AdColonyAdapter(GADMAdapterAdColony.o)
  "_OBJC_CLASS_$_AdColonyAdOptions", referenced from:
      objc-class-ref in AdColonyAdapter(GADMAdapterAdColony.o)
  "_OBJC_CLASS_$_AdColonyUserMetadata", referenced from:
      objc-class-ref in AdColonyAdapter(GADMAdapterAdColony.o)
  "_ADCUserMale", referenced from:
      -[AdColonyInitializer getAppOptionsFromRequest:] in AdColonyAdapter(GADMAdapterAdColony.o)
  "_ADCUserFemale", referenced from:
      -[AdColonyInitializer getAppOptionsFromRequest:] in AdColonyAdapter(GADMAdapterAdColony.o)
ld: symbol(s) not found for architecture x86_64**

**XCode Version 8.2.1**. added in Link Binary with libraries - **libz.tbd**.

I thinks problems or i not added all files in sections "**Link Binary with libraries** " or in section "**Other Linker Flags**" is conflict of parameters or anything else. Do you have any thinks?

**Comment by cmanibog-ac** [comment]
I've reached out to our Engineering team for additional guidance. I will follow up with more information or additional questions after they review these details.

**Comment by cmanibog-ac** [comment]
To look into this further, would you be able to provide a framework for Frameworks and linker flags in the project settings? For clarification, is this integration through CocoaPods or a manual integration?

**Comment by cmanibog-ac** [comment]
@tigrim - If you are still experiencing this issue, please email our support team at support@adcolony.com. In your message please provide a framework for Frameworks and linker flags in the project settings? For clarification, is this integration through CocoaPods or a manual integration?
