### ISSUE TITLE
No way to know when ad has finished closing

### ISSUE THREAD

**Issue by ninjudd** [AdColony/AdColony-iOS-SDK-3#24]
We need a callback to know when an ad has closed completely. The current `onClose` callback is called before the `ADCContainer` has finished being dismissed. We need to present a new controller once the ad is done, but currently our only option is to sleep and wait.

**Comment by cmanibog-ac** [comment]
I've reached out to our Engineering team for additional insight on this. We will follow up with more information after looking into this further.

**Comment by cmanibog-ac** [comment]
@ninjudd Apologies for the delay. To look into this further, could you clarify if a mediation layer is being used and if yes, which partner? Could you give us the steps that are followed to reproduce this behavior? Please also send a console log showing the app activity from when our SDK is initialized through this issue. For more streamlined communication with our teams, feel free to submit this as a ticket to our Support team at support@adcolony.com.
