### ISSUE TITLE
AdColony [*** ERROR ***] : Tried to show an expired interstitial ad.

### ISSUE THREAD

**Issue by Borisevich34** [AdColony/AdColony-iOS-SDK-3#25]
Could you give a description of this error, please?
It is displayed after call showWithPresentingViewController method of AdColonyInterstitial object.
How can I handle this error after call the method above?

This error is happened sometimes, AdColony IOS SDK version is 3.1.0 from pods. IOS version is 10.0.

**Comment by cmanibog-ac** [comment]
It is possible for our ads to to expire if the app has been inactive for a while. Our sample app shows how to handle such an event: https://github.com/AdColony/AdColony-iOS-SDK-3/blob/master/SampleApps/ObjC/AdColonyBasic/AdColonyBasic/ViewController.m
