### ISSUE TITLE
AdColony [*** ERROR ***] : AdColony has ads, but could not display them. AdColony was unable to find the currently visible UIViewController for your app. Please ensure that your key UIWindow has a rootViewController.

### ISSUE THREAD

**Issue by troyzhao** [AdColony/AdColony-iOS-SDK-3#26]
what the hell, i had already set rootViewController, but still get an error!
my code like this

UIViewController *rootCtl = [UIApplication sharedApplication].windows[0].rootViewController;
[self.ad showWithPresentingViewController:rootCtl];

And the log:

AdColony [Info] : Interstitial ad request succeeded in zone: vzxxxxxxxxxxxxx
AdColony [*** ERROR ***] : AdColony has ads, but could not display them. AdColony was unable to find the currently visible UIViewController for your app. Please ensure that your key UIWindow has a rootViewController.
AdColony [Info] : Interstitial ad started playing in zone: vzxxxxxxxxxxxx

**Comment by cmanibog-ac** [comment]
@troyzhao Could I have you check that our Setup documentation has been followed at https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup? Could you also confirm that this activity is called on the main thread? If this is the case, please share a console log showing the app activity from when our SDK is initialized through this error message along with the code snippet where the AdColony SDK is invoked to display ads. 

For streamlined communication with our Support/Tech team, feel free to send this information as a support ticket to support@adcolony.com.

**Comment by troyzhao** [comment]
OK, it works when i reconfiguration the xcode project setup, but i still don`t know what happened.
