### ISSUE TITLE
Crash with Landscape orientation

### ISSUE THREAD

**Issue by tigrim** [AdColony/AdColony-iOS-SDK-3#28]
I have got next error **"preferredInterfaceOrientationForPresentation 'landscapeRight' must match a supported interface orientation: 'portrait'!"**. I have UiViewController with next metods 

- (BOOL)shouldAutorotate {
    return NO;
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    return **UIInterfaceOrientationPortrait**;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return **UIInterfaceOrientationMaskPortrait**;
}

i have Use admob mediation. Problem only with  AdColony. Other Advertising networks work good. Problem has only in landscape orientation. If will change of supportedInterfaceOrientations on **UIInterfaceOrientationMaskAll** i don't have crash, but my main **UIViewController** will change your orientation on landscape. It is necessary that the **UIViewController** remains in the portrait orientation. Please, help me with it
![2017-08-19 17 31 32](https://user-images.githubusercontent.com/17082167/29487779-8b335814-8507-11e7-9790-de7789a81aee.png)

**Comment by cmanibog-ac** [comment]
To look into this further, could you let me know if this app supports portrait orientation only? Could I have you check that you have followed our Project Setup documentation, specifically the supported orientations section at https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup#configuring-supported-orientations. Could you also confirm if this is with our latest 3.1.1 iOS SDK and please share a full console log showing the app activity from when our SDK is initialized through the crash. 

For streamlined communication with our Support team, feel free to submit this as a ticket to support@adcolony.com.
