### ISSUE TITLE
Interstitial is shown behind the main window on IOS

### ISSUE THREAD

**Issue by SamuraiCoder** [AdColony/AdColony-iOS-SDK-3#29]
Hi,

I'm implementing interstitials in our games. Everything is correct but once I press a button to show the ad fullscreen I can hear the demo sound of interstitial but the game window remains with the same as before and the ad is not displayed.

This is when I trigger for now the add:

 ```
GameWindowiOS* gameWindow = gh_safe_cast<GameWindowiOS*>(Application::Instance()->GetGameWindow());
            if (gameWindow)
            {
                GameViewController* gameViewController = gameWindow->GetGameViewController();
                if (gameViewController)
                {
                    //[ad showWithPresentingViewController: gameViewController];
                    [ad showWithPresentingViewController: (UIViewController*) gameViewController];
                }
            }
        }

```
GameWindowIOS implements an interface for the game window and we can get the GameViewController for it. We create the windows in this way:

```
m_Window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];
m_GameViewController = [[GameViewController alloc] initWithFrame:UIScreen.mainScreen.bounds];
m_Window.rootViewController = m_GameViewController;
```

Also GameViewController is a view that holds the game in this way:

```
@interface AutoRotatingViewController : UIViewController
+ (NSUInteger)getSupportedInterfaceOrientations;
@end

@interface GameViewController : AutoRotatingViewController...
```

So what I'm doing wrong? The ad is working but not show on top of all the windows...

Thanks,

Sam.

**Comment by cmanibog-ac** [comment]
See email thread https://adcolony.desk.com/agent/case/23969
