### ISSUE TITLE
Duplicate symbol error

### ISSUE THREAD

**Issue by euroboy** [AdColony/AdColony-iOS-SDK-3#3]
After installing AdColony iOS SDK 3, I'm facing the following error:

`duplicate symbol _OBJC_IVAR_$_GCDWebServerBodyEncoder._response in:
    /Users/me/Library/Developer/Xcode/DerivedData/myapp/Build/Products/Debug-iphoneos/GCDWebServer/libGCDWebServer.a(GCDWebServerResponse.o)
    /Users/me/Documents/My project/Pods/AdColony/AdColony.framework/AdColony(GCDWebServerResponse.o)`

In my project I've installed GCDWebServer via cocoapods. Does it also is containing in AdColony framework? How to solve this?

**Comment by octover** [comment]
We are using Ad Colony via Ad Marvel, and have the same problem. We can't/won't try and piggy back on your inclusion of GCDWebServer, so please sort this out. I would suggest namespacing your GCDWebServer to something like ACGCDWebServer so it doesn't conflict.

**Comment by owainm** [comment]
Fix is available in v3.0.6
