### ISSUE TITLE
NSAllowsArbitraryLoads = false, really?

### ISSUE THREAD

**Issue by torufuruya** [AdColony/AdColony-iOS-SDK-3#31]
https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup#step-3-configuring-app-transport-security-ats
Regarding to Option 2, you updated NSAllowsArbitraryLoads to be false at 3.2.0, but is it true?

**Comment by gswati8** [comment]
Yes, by setting NSAllowsArbitraryLoads to be false, ATS is enabled and that is supported by 3.2 SDK. However, please make sure that the following keys are set to true NSAllowsLocalNetworking and NSAllowsArbitraryLoadsInWebContent for the SDK to render ads.

**Comment by torufuruya** [comment]
Does it work without NSAllowsArbitraryLoads as following?

```xml
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsLocalNetworking</key>
<true/>
<key>NSAllowsArbitraryLoadsInWebContent</key>
<true/>
</dict>
```

How about iOS 9?

**Comment by gswati8** [comment]
The keys NSAllowsLocalNetworking and NSAllowsArbitraryLoadsInWebContent are available on iOS 10 and above, thus on iOS9 they have no effect. So if the combinations (option#2) is used on iOS 9 and lower, it will enable ATS and ADcolony SDK will not be able to render ads.
