### ISSUE TITLE
Thread lock issue on iOS 11?

### ISSUE THREAD

**Issue by SuperEntertainmentSteve** [AdColony/AdColony-iOS-SDK-3#32]
I updated to sdk 3.2.0.0 as previous versions weren't working on iOS 11.
Things started working on the first run, but then on subsequent runs of the app the game hangs a few seconds in. 

I paused execution in xCode and it looks like an issue inside AdColony.

![adcolonythreadlock](https://user-images.githubusercontent.com/31723027/30149963-036b8e0c-93ed-11e7-8a13-6658e2186023.png)

**Comment by cmanibog-ac** [comment]
Thanks for bringing this to our attention. Our team has opened a bug for this and will be working on a resolution.

**Comment by anandjp** [comment]
@SuperEntertainmentSteve, please call setAppOptions outside completion handler and you will not see this issue.

**Comment by ekilah** [comment]
@anandjp I work for Heyzap, the mediation SDK being used in this screenshot/issue. @SuperEntertainmentSteve reached out to us to point this out to us (thanks for that).

@anandjp - what can and can't be done in the completion handler? Would it be sufficient for us to just use a `dispatch_async` block inside your completion handler to set these options and also configure zone callbacks?

**Comment by anandjp** [comment]
Can you please email support@adcolony.com<mailto:support@adcolony.com> with code block you are planning to use along with usecase for calling setOptions in completion handler?


Sent from my iPhone

On Sep 11, 2017, at 5:18 PM, Monroe Ekilah <notifications@github.com<mailto:notifications@github.com>> wrote:


@anandjp<https://github.com/anandjp> I work for Heyzap, the mediation SDK being used in this screenshot/issue. @SuperEntertainmentSteve<https://github.com/superentertainmentsteve> reached out to us to point this out to us (thanks for that).

@anandjp<https://github.com/anandjp> - what can and can't be done in the completion handler? Would it be sufficient for us to just use a dispatch_async block inside your completion handler to set these options and also configure zone callbacks?

**Comment by ekilah** [comment]
the usecase is just to set up the logging behavior of the AdColony SDK after it initializes. the rest of the code there sets up the incentivized zone callbacks. we'll just do this asynchronously after the completion block is received. thanks.

I was unable to reproduce the lock that @SuperEntertainmentSteve reported but we'll do this just in case.

**Comment by ekilah** [comment]
Heyzap released a patch to our current beta SDK, version 9.13.1, with a workaround for this, though I couldn't reproduce the issue myself in the simulator. [Changelog here](https://developers.heyzap.com/docs/changelog) . Let us know if anything else comes up @SuperEntertainmentSteve , thanks for the report!
