### ISSUE TITLE
In Airplane Mode, showWithPresentingViewController will not playAd and trigger no callbacks.

### ISSUE THREAD

**Issue by jus18tin** [AdColony/AdColony-iOS-SDK-3#35]
and (BOOL)showWithPresentingViewController will return YES, Although no ad has been playback.
Because even the ad.close will not be triggered, We have no idea when our app has been come back to our control in that case.

**Comment by cmanibog-ac** [comment]
The API showWithPresentingViewController returns that the SDK will begin showing a video, not that it has shown a video. A workaround for this is to check that an internet connection is available using Apple's SCNetworkReachability API before invoking showWithPresentingViewController.

**Comment by jus18tin** [comment]
At AdColony-iOS-SDK-2.6.3,
in that case,"zoneStatusForZone" will become false, and "onAdColonyAdAvailabilityChange" with "available" false will be triggered.
It would be helpfully if you add something like ad.fail in next version
