### ISSUE TITLE
Adcolony shows black screen instead of rewarded video

### ISSUE THREAD

**Issue by RackovychV** [AdColony/AdColony-iOS-SDK-3#4]
Now on my ipad 3 when I call showWithPresentingViewController, instead of ads video there is only black screen without buttons and I can't close it.

**Comment by mwhite-ac** [comment]
This is an issue that needs deeper review through our team escalation process.  Please email support@adcolony.com and include a full console log showing all app activity from when you initalize our SDK through the video view and this issue.

**Comment by owainm** [comment]
Fix is available in v3.0.6.
