### ISSUE TITLE
Presenting ad from Modal Presentation bug

### ISSUE THREAD

**Issue by robertodias180** [AdColony/AdColony-iOS-SDK-3#40]
Hello,

With the new version (3.2.1) if a present the ad from a View Controller that is presented as a Modal when the ad closes the main View Controler is gone. 

I can provide a test case if needed.

thanks

**Comment by gswati8** [comment]
Can you please share the  UIModalPresentationStyle being used to present the ModalViewController.

**Comment by robertodias180** [comment]
Here is the code 😃 

`
        let vc = storyboard!.instantiateViewController(withIdentifier: "PopupViewController")
        vc.modalPresentationStyle = .custom
        vc.modalTransitionStyle = .crossDissolve
        self.present(vc, animated: true)
`

**Comment by gswati8** [comment]
Sorry to know that you are facing issues. We will be releasing SDK 3.3 soon, and it has the fix for the issue reported. The modal viewController presenting the ad will not be dismissed once the ad finishes playing.
