### ISSUE TITLE
iPhone X, can't close or repeat video

### ISSUE THREAD

**Issue by meeeeeepo** [AdColony/AdColony-iOS-SDK-3#41]
![iPhoneX](http://joxi.ru/p27KbWec0Yayk2.png)

**Comment by cmanibog-ac** [comment]
@meeeeeepo Our team is aware of the display issues with ads on the iPhone X and are working towards a fix. I'll need to sync up with our Engineering team for a more accurate date of when this update will be released.

**Comment by cmanibog-ac** [comment]
Apologies for the delay. We have recently released our v3.3 iOS SDK update. This display issue has been corrected in this SDK update.
