### ISSUE TITLE
Crash on v.3.2.1: Fatal Exception: NSRangeException

### ISSUE THREAD

**Issue by egzy1992** [AdColony/AdColony-iOS-SDK-3#42]
Hello,

Using AdColony SDK v3.2.1 we have the following crash
ADCLogManager.m line 203
__30-[ADCLogManager propogateLogs]_block_invoke_2

Fabric reports:
__30-[ADCLogManager propogateLogs]_block_invoke_2
 Raw Text

`#10. Crashed: AdColony Worker
0  BoxingTimer                    0x100476e70 CLSProcessRecordAllThreads + 4299714160
1  BoxingTimer                    0x100476e70 CLSProcessRecordAllThreads + 4299714160
2  BoxingTimer                    0x100476d2c CLSProcessRecordAllThreads + 4299713836
3  BoxingTimer                    0x100466af8 CLSHandler + 4299647736
4  BoxingTimer                    0x100474e78 __CLSExceptionRecord_block_invoke + 4299705976
5  libdispatch.dylib              0x189db69a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x189dc3ee0 _dispatch_barrier_sync_f_invoke + 84
7  BoxingTimer                    0x10047490c CLSExceptionRecord + 4299704588
8  BoxingTimer                    0x100474734 CLSExceptionRecordNSException + 4299704116
9  BoxingTimer                    0x100474348 CLSTerminateHandler() + 4299703112
10 libc++abi.dylib                0x18994f5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18994f1a8 __cxa_rethrow + 144
12 libobjc.A.dylib                0x1899606f8 objc_exception_rethrow + 44
13 CoreFoundation                 0x18addae10 CFRunLoopRunSpecific + 532
14 Foundation                     0x18b8f5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
15 BoxingTimer                    0x1001bfbc4 -[AdColony setupWorkerThread] (AdColony.m:156)
16 Foundation                     0x18b9f3318 __NSThread__start__ + 996
17 libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
18 libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
19 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

--

Fatal Exception: NSRangeException
0  CoreFoundation                 0x18aefefe0 __exceptionPreprocess
1  libobjc.A.dylib                0x189960538 objc_exception_throw
2  CoreFoundation                 0x18aeefcfc -[__NSArrayM removeObjectsInRange:]
3  BoxingTimer                    0x100197464 __30-[ADCLogManager propogateLogs]_block_invoke_2 (ADCLogManager.m:203)
4  Foundation                     0x18b9f350c __NSThreadPerformPerform
5  CoreFoundation                 0x18aead42c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
6  CoreFoundation                 0x18aeacd9c __CFRunLoopDoSources0
7  CoreFoundation                 0x18aeaa9a8 __CFRunLoopRun
8  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific
9  Foundation                     0x18b8f5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
10 BoxingTimer                    0x1001bfbc4 -[AdColony setupWorkerThread] (AdColony.m:156)
11 Foundation                     0x18b9f3318 __NSThread__start__
12 libsystem_pthread.dylib        0x189fc168c _pthread_body
13 libsystem_pthread.dylib        0x189fc159c _pthread_body
14 libsystem_pthread.dylib        0x189fbecb4 thread_start

#0. com.apple.main-thread
0  CoreFoundation                 0x18adef450 CFStringFindWithOptionsAndLocale + 1096
1  CoreFoundation                 0x18adf6fdc CFStringFind + 248
2  CoreText                       0x18dc06880 SplitStringAtSeparator(__CFString const*, __CFString const*, CFRange*, CFRange*) + 52
3  CoreText                       0x18db25944 CreateFontInfoDictionaryFromFontURL(__CFURL const*) + 380
4  CoreText                       0x18db25784 CreateFontsWithURL(__CFURL const*, bool) + 96
5  CoreText                       0x18db2558c CreateFontWithFontURL(__CFURL const*, bool) + 60
6  CoreText                       0x18db22974 TCGFontCache::CopyFont(__CFURL const*, bool) const + 156
7  CoreText                       0x18db227d8 TBaseFont::CopyNativeFont() const + 152
8  CoreText                       0x18db2271c TBaseFont::CopyGraphicsFont() const + 24
9  CoreText                       0x18db5ac28 TBaseFont::GetCommonTable(unsigned int, unsigned int*) const + 1060
10 CoreText                       0x18db25f7c TBaseFont::GetUnicodeEncoding() const + 68
11 CoreText                       0x18db3d768 TBaseFont::GetGlyphsForCharacterRange(CFRange, unsigned short*) const + 56
12 CoreText                       0x18db3379c CTFontGetGlyphsAndAdvancesForCharacterRange + 212
13 GraphicsServices               0x18c83ee18 GSFontGetLatin1LayoutInfo + 140
14 UIFoundation                   0x190fce634 -[UIFont(UIFont_AttributedStringDrawing) _getLatin1GlyphMapping:andAdvanceMapping:] + 20
15 UIFoundation                   0x190f9e708 __NSStringDrawingEngine + 3308
16 UIFoundation                   0x190fa442c -[NSAttributedString(NSExtendedStringDrawing) boundingRectWithSize:options:context:] + 588
17 BoxingTimer                    0x1000c895c -[UILabel(DynamicFontSize) adjustFontSizeToFillItsContents] (UILabel+DynamicFontSize.m:27)
18 BoxingTimer                    0x1000b5f94 -[BTBaseViewController checkLabelFont] (BTBaseViewController.m:688)
19 UIKit                          0x19112a588 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 268
20 UIKit                          0x19112a3f4 -[_UIViewControllerTransitionContext __runAlongsideAnimations] + 188
21 UIKit                          0x1916fbaa4 __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke_2 + 192
22 UIKit                          0x19132d388 +[UIView(Internal) _performBlockDelayingTriggeringResponderEvents:] + 220
23 UIKit                          0x1916fb894 __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke + 136
24 UIKit                          0x1916fb778 -[_UIWindowRotationAnimationController animateTransition:] + 516
25 UIKit                          0x191302e68 -[UIWindow _rotateToBounds:withAnimator:transitionContext:] + 616
26 UIKit                          0x191304608 -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:] + 1232
27 UIKit                          0x1910af43c -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:] + 548
28 UIKit                          0x1910af0bc -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] + 148
29 UIKit                          0x1910a5c54 __57-[UIWindow _updateToInterfaceOrientation:duration:force:]_block_invoke + 124
30 UIKit                          0x191031ca8 -[UIWindow _updateToInterfaceOrientation:duration:force:] + 472
31 CoreFoundation                 0x18ae995f4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
32 CoreFoundation                 0x18ae98d08 _CFXRegistrationPost + 400
33 CoreFoundation                 0x18ae98a84 ___CFXNotificationPost_block_invoke + 60
34 CoreFoundation                 0x18af077a8 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1412
35 CoreFoundation                 0x18addc95c _CFXNotificationPost + 376
36 Foundation                     0x18b8ef970 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
37 UIKit                          0x1910317f4 -[UIDevice setOrientation:animated:] + 324
38 UIKit                          0x1912c85c4 -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 2240
39 UIKit                          0x1912c7a90 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 448
40 UIKit                          0x1912b30ec __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 152
41 UIKit                          0x1912b2d68 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 892
42 UIKit                          0x1915ed360 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 464
43 FrontBoardServices             0x18ca7b22c __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.376 + 208
44 FrontBoardServices             0x18caa8884 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
45 FrontBoardServices             0x18caa86f0 -[FBSSerialQueue _performNext] + 176
46 FrontBoardServices             0x18caa8aa0 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
47 CoreFoundation                 0x18aead42c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
48 CoreFoundation                 0x18aeacd9c __CFRunLoopDoSources0 + 540
49 CoreFoundation                 0x18aeaa9a8 __CFRunLoopRun + 744
50 CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
51 GraphicsServices               0x18c845074 GSEventRunModal + 100
52 UIKit                          0x191095c9c UIApplicationMain + 208
53 BoxingTimer                    0x1000c566c main (main.m:14)
54 libdyld.dylib                  0x189de959c start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  CoreFoundation                 0x18aeace90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18aeaaae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x18b8f5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x18b916b84 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x191a1f830 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x18b9f3318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
10 libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
11 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  BoxingTimer                    0x1004619c8 CLSMachExceptionServer + 4299626952
3  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
4  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
5  libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  CoreFoundation                 0x18aeace90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18aeaaae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x18b5e7df4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x18b9f3318 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
8  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
9  libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#4. Thread
0  libsystem_kernel.dylib         0x189edb314 swtch_pri + 8
1  libsystem_pthread.dylib        0x189fc1e84 sched_yield + 16
2  JavaScriptCore                 0x18f78ff90 bmalloc::StaticMutex::lockSlowCase() + 108
3  JavaScriptCore                 0x18f78ef78 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 224
4  JavaScriptCore                 0x18f78ee7c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
5  JavaScriptCore                 0x18f78ed5c std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 34
6  JavaScriptCore                 0x18f78f00c void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
7  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
8  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
9  libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#5. WebThread
0  libsystem_kernel.dylib         0x189ef8e64 __psynch_mutexwait + 8
1  libsystem_pthread.dylib        0x189fc4b8c _pthread_mutex_lock_wait + 96
2  libsystem_pthread.dylib        0x189fc4d94 _pthread_mutex_lock_slow + 300
3  WebCore                        0x18faaf330 _WebTryThreadLock(bool) + 128
4  WebCore                        0x18faaf290 WebRunLoopLock(__CFRunLoopObserver*, unsigned long, void*) + 44
5  CoreFoundation                 0x18aeac9a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
6  CoreFoundation                 0x18aeaa630 __CFRunLoopDoObservers + 372
7  CoreFoundation                 0x18aeaac18 __CFRunLoopRun + 1368
8  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
9  WebCore                        0x18faacd3c RunWebThread(void*) + 456
10 libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
11 libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
12 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#6. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  CoreFoundation                 0x18aeace90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18aeaaae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
5  AVFAudio                       0x1a51214f4 GenericRunLoopThread::Entry(void*) + 164
6  AVFAudio                       0x1a5147814 CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
8  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
9  libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#7. WebCore: LocalStorage
0  libsystem_kernel.dylib         0x189ef8e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x189fc0814 _pthread_cond_wait + 640
2  JavaScriptCore                 0x18ede29a4 WTF::ThreadCondition::timedWait(WTF::Mutex&, double) + 80
3  JavaScriptCore                 0x18f775a68 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2256
4  WebKitLegacy                   0x190d1d0a8 bool WTF::ConditionBase::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 172
5  WebKitLegacy                   0x190d1fd40 std::__1::unique_ptr<WTF::Function<void ()>, std::__1::default_delete<WTF::Function<void ()> > > WTF::MessageQueue<WTF::Function<void ()> >::waitForMessageFilteredWithTimeout<WTF::MessageQueue<WTF::Function<void ()> >::waitForMessage()::'lambda'(WTF::Function<void ()> const&)>(WTF::MessageQueueWaitResult&, WTF::MessageQueue<WTF::Function<void ()> >::waitForMessage()::'lambda'(WTF::Function<void ()> const&)&&, WTF::WallTime) + 144
6  WebKitLegacy                   0x190d1f348 WebCore::StorageThread::threadEntryPoint() + 68
7  JavaScriptCore                 0x18eddef7c WTF::threadEntryPoint(void*) + 212
8  JavaScriptCore                 0x18eddee8c WTF::wtfThreadEntryPoint(void*) + 24
9  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
10 libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
11 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#8. com.apple.coreaudio.AQClient
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  CoreFoundation                 0x18aeace90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18aeaaae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
5  AudioToolbox                   0x18de6696c GenericRunLoopThread::Entry(void*) + 164
6  AudioToolbox                   0x18e03a4c8 CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
8  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
9  libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  CoreFoundation                 0x18aeace90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18aeaaae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
5  TTSSpeechBundle                0x10800e570 (Missing)
6  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
7  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
8  libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#10. Crashed: AdColony Worker
0  BoxingTimer                    0x100476e70 CLSProcessRecordAllThreads + 4299714160
1  BoxingTimer                    0x100476e70 CLSProcessRecordAllThreads + 4299714160
2  BoxingTimer                    0x100476d2c CLSProcessRecordAllThreads + 4299713836
3  BoxingTimer                    0x100466af8 CLSHandler + 4299647736
4  BoxingTimer                    0x100474e78 __CLSExceptionRecord_block_invoke + 4299705976
5  libdispatch.dylib              0x189db69a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x189dc3ee0 _dispatch_barrier_sync_f_invoke + 84
7  BoxingTimer                    0x10047490c CLSExceptionRecord + 4299704588
8  BoxingTimer                    0x100474734 CLSExceptionRecordNSException + 4299704116
9  BoxingTimer                    0x100474348 CLSTerminateHandler() + 4299703112
10 libc++abi.dylib                0x18994f5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18994f1a8 __cxa_rethrow + 144
12 libobjc.A.dylib                0x1899606f8 objc_exception_rethrow + 44
13 CoreFoundation                 0x18addae10 CFRunLoopRunSpecific + 532
14 Foundation                     0x18b8f5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
15 BoxingTimer                    0x1001bfbc4 -[AdColony setupWorkerThread] (AdColony.m:156)
16 Foundation                     0x18b9f3318 __NSThread__start__ + 996
17 libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
18 libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
19 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#11. com.mopub.MPNetworkManager
0  libsystem_kernel.dylib         0x189edb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x189edb09c mach_msg + 72
2  CoreFoundation                 0x18aeace90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18aeaaae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x18addada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x18b8f5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x18b94a704 -[NSRunLoop(NSRunLoop) run] + 88
7  BoxingTimer                    0x1008fa284 -[MPNetworkManager networkThreadMain] + 3954636
8  Foundation                     0x18b9f3318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
10 libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
11 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#12. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#13. CTTelephonyNetworkInfo
0  libsystem_kernel.dylib         0x189ef8e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x189fc0814 _pthread_cond_wait + 640
2  Foundation                     0x18b9cce20 -[__NSOperationInternal _waitUntilFinished:] + 132
3  Foundation                     0x18b8f2530 -[__NSObserver _doit:] + 232
4  CoreFoundation                 0x18ae995f4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
5  CoreFoundation                 0x18ae98d08 _CFXRegistrationPost + 400
6  CoreFoundation                 0x18ae98a84 ___CFXNotificationPost_block_invoke + 60
7  CoreFoundation                 0x18af077a8 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1412
8  CoreFoundation                 0x18addc95c _CFXNotificationPost + 376
9  Foundation                     0x18b8ef970 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
10 CoreTelephony                  0x18d921dcc -[CTTelephonyNetworkInfo handleNotificationFromConnection:ofType:withInfo:] + 544
11 CoreTelephony                  0x18d92113c _ServerConnectionCallback(__CTServerConnection*, __CFString const*, __CFDictionary const*, void*) + 136
12 CoreTelephony                  0x18d93d0a0 ___ZNK13CTServerState21sendNotification_syncE7CTEventPK10__CFStringPK14__CFDictionary_block_invoke.17 + 32
13 libdispatch.dylib              0x189db69e0 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x189db69a0 _dispatch_client_callout + 16
15 libdispatch.dylib              0x189dc4ad4 _dispatch_queue_serial_drain + 928
16 libdispatch.dylib              0x189dba2cc _dispatch_queue_invoke + 884
17 libdispatch.dylib              0x189dc6a50 _dispatch_root_queue_drain + 540
18 libdispatch.dylib              0x189dc67d0 _dispatch_worker_thread3 + 124
19 libsystem_pthread.dylib        0x189fbf100 _pthread_wqthread + 1096
20 libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#14. Thread
0  libsystem_pthread.dylib        0x189fbeca8 start_wqthread + 126

#15. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbefd0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#16. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#17. com.apple.CoreLocation.ConnectionClient.0x174325a00.events
0  libsystem_kernel.dylib         0x189edb278 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x189dc96b4 _os_semaphore_timedwait + 92
2  libdispatch.dylib              0x189dc8c5c _dispatch_semaphore_wait_slow + 72
3  CoreLocation                   0x193175078 (null) + 648
4  CoreLocation                   0x19317a440 (null) + 2184
5  CoreLocation                   0x1931c6018 (null) + 74940
6  CoreLocation                   0x1931c3b0c (null) + 65456
7  libxpc.dylib                   0x189ff384c _xpc_connection_call_event_handler + 68
8  libxpc.dylib                   0x189ff77cc do_mach_notify_port_destroyed + 124
9  libxpc.dylib                   0x189ff771c _Xmach_notify_port_destroyed + 80
10 libxpc.dylib                   0x189ff76a0 notify_server + 92
11 libxpc.dylib                   0x189ffca10 _xpc_connection_pass2mig + 164
12 libxpc.dylib                   0x189ff12e8 _xpc_connection_mach_event + 1336
13 libdispatch.dylib              0x189db6a70 _dispatch_client_callout4 + 16
14 libdispatch.dylib              0x189dba5f0 _dispatch_mach_msg_invoke + 312
15 libdispatch.dylib              0x189dc4964 _dispatch_queue_serial_drain + 560
16 libdispatch.dylib              0x189db9a2c _dispatch_mach_invoke + 672
17 libdispatch.dylib              0x189dc4964 _dispatch_queue_serial_drain + 560
18 libdispatch.dylib              0x189dba2cc _dispatch_queue_invoke + 884
19 libdispatch.dylib              0x189dc4964 _dispatch_queue_serial_drain + 560
20 libdispatch.dylib              0x189dba2cc _dispatch_queue_invoke + 884
21 libdispatch.dylib              0x189dc6a50 _dispatch_root_queue_drain + 540
22 libdispatch.dylib              0x189dc67d0 _dispatch_worker_thread3 + 124
23 libsystem_pthread.dylib        0x189fbf100 _pthread_wqthread + 1096
24 libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#18. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#19. com.apple.CoreLocation.ConnectionClient.0x174328160.events
0  libsystem_kernel.dylib         0x189edb278 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x189dc96b4 _os_semaphore_timedwait + 92
2  libdispatch.dylib              0x189dc8c5c _dispatch_semaphore_wait_slow + 72
3  CoreLocation                   0x193175078 (null) + 648
4  CoreLocation                   0x19317a440 (null) + 2184
5  CoreLocation                   0x1931c6018 (null) + 74940
6  CoreLocation                   0x1931c3b0c (null) + 65456
7  libxpc.dylib                   0x189ff384c _xpc_connection_call_event_handler + 68
8  libxpc.dylib                   0x189ff77cc do_mach_notify_port_destroyed + 124
9  libxpc.dylib                   0x189ff771c _Xmach_notify_port_destroyed + 80
10 libxpc.dylib                   0x189ff76a0 notify_server + 92
11 libxpc.dylib                   0x189ffca10 _xpc_connection_pass2mig + 164
12 libxpc.dylib                   0x189ff12e8 _xpc_connection_mach_event + 1336
13 libdispatch.dylib              0x189db6a70 _dispatch_client_callout4 + 16
14 libdispatch.dylib              0x189dba5f0 _dispatch_mach_msg_invoke + 312
15 libdispatch.dylib              0x189dc4964 _dispatch_queue_serial_drain + 560
16 libdispatch.dylib              0x189db9a2c _dispatch_mach_invoke + 672
17 libdispatch.dylib              0x189dc4964 _dispatch_queue_serial_drain + 560
18 libdispatch.dylib              0x189dba2cc _dispatch_queue_invoke + 884
19 libdispatch.dylib              0x189dc4964 _dispatch_queue_serial_drain + 560
20 libdispatch.dylib              0x189dba2cc _dispatch_queue_invoke + 884
21 libdispatch.dylib              0x189dc6a50 _dispatch_root_queue_drain + 540
22 libdispatch.dylib              0x189dc67d0 _dispatch_worker_thread3 + 124
23 libsystem_pthread.dylib        0x189fbf100 _pthread_wqthread + 1096
24 libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#20. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#21. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#22. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#23. Thread
0  libsystem_kernel.dylib         0x189ef9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x189fbf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x189fbecac start_wqthread + 4

#24. WTF::AutomaticThread
0  libsystem_kernel.dylib         0x189edb314 swtch_pri + 8
1  libsystem_pthread.dylib        0x189fc1e84 sched_yield + 16
2  JavaScriptCore                 0x18f3eb814 JSC::Heap::resumeTheWorld() + 452
3  JavaScriptCore                 0x18f3ed7f4 JSC::Heap::collectInThread() + 1668
4  JavaScriptCore                 0x18f3efd50 JSC::Heap::Thread::work() + 16
5  JavaScriptCore                 0x18f7657f4 std::__1::__function::__func<WTF::AutomaticThread::start(WTF::Locker<WTF::LockBase> const&)::$_0, std::__1::allocator<WTF::AutomaticThread::start(WTF::Locker<WTF::LockBase> const&)::$_0>, void ()>::operator()() + 352
6  JavaScriptCore                 0x18eddef7c WTF::threadEntryPoint(void*) + 212
7  JavaScriptCore                 0x18eddee8c WTF::wtfThreadEntryPoint(void*) + 24
8  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
9  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
10 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4

#25. WTF::AutomaticThread
0  libsystem_kernel.dylib         0x189ef8e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x189fc0814 _pthread_cond_wait + 640
2  JavaScriptCore                 0x18ede29e8 WTF::ThreadCondition::timedWait(WTF::Mutex&, double) + 148
3  JavaScriptCore                 0x18f775a68 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2256
4  JavaScriptCore                 0x18f3479d8 bool WTF::ConditionBase::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 172
5  JavaScriptCore                 0x18f765760 std::__1::__function::__func<WTF::AutomaticThread::start(WTF::Locker<WTF::LockBase> const&)::$_0, std::__1::allocator<WTF::AutomaticThread::start(WTF::Locker<WTF::LockBase> const&)::$_0>, void ()>::operator()() + 204
6  JavaScriptCore                 0x18eddef7c WTF::threadEntryPoint(void*) + 212
7  JavaScriptCore                 0x18eddee8c WTF::wtfThreadEntryPoint(void*) + 24
8  libsystem_pthread.dylib        0x189fc168c _pthread_body + 240
9  libsystem_pthread.dylib        0x189fc159c _pthread_body + 282
10 libsystem_pthread.dylib        0x189fbecb4 thread_start + 4`

Thanks a lot!
The app is in production, I don't have a way to reproduce the crash.

Egor

**Comment by cmanibog-ac** [comment]
@egzy1992 Our Engineering team was able to review this crash. We are aware of this and a fix will be implemented in our 3.3 SDK update. We are targeting this release to be in the next couple of weeks.

**Comment by cmanibog-ac** [comment]
Sorry for the delayed response. We have pushed a fix on our backend that should resolve this crash. Could you confirm if you are still seeing this crash or if the crashes have subsided?
