### ISSUE TITLE
Sometimes AdColony Reward Callback isn't called in iOS

### ISSUE THREAD

**Issue by flyme2moon** [AdColony/AdColony-iOS-SDK-3#43]
I've serviced mobile games with AdColony for 2 years.
My game gives reward to users after watching Ad.
However recently I got lots of email from iOS users about Ad reward problem.
It suddenly happens from 13th December.
(I didn't modify any code. Game has been released long time ago)
I found out that sometimes AdColony Reward CallBack isn't called after watching Ad in iOS.
I use AdColony library version: 3.1.1.2 64-bit production iOS.

This is some logs about this issue.

When Ad reward works well i can find next log.
=> Dec 19 10:48:23 minjiui-iPhone MonsterBusters[1275] <Notice>: AdColony [Info] : Reward: 2 Coin in zone: vz12b6a7e49dc845b084

However when Ad reward doesn't work well
=> Dec 18 18:24:44 playdog-ipadmini2 MonsterBusters[204] <Warning>: AdColony: Request failed with error: No fill for ad request and suggestion: Make sure you have configured your zone properly in the control panel: http://clients.adcolony.com.
Dec 18 18:24:44 playdog-ipadmini2 MonsterBusters[204] <Warning>: AdColony [Info] : Interstitial ad finished playing in zone: vz12b6a7e49dc845b084

I think that AdColony Reward Callback isn't called when Ad preloading fails.
I call [AdColony requestInterstitialInZone...] to preload Ad in next case.
- When game is initialized.
- When Ad is closed.
- When Ad is expired.

**Comment by sohos** [comment]
Same issue here. I have two games and both stopped at the same time.

**Comment by gswati8** [comment]
To look into this further, please share the entire console log and Charles logs for our team to review.Also, can you please confirm which version of SDK are you using. Kindly send this through support@adcolony.com for streamlined communication.
