### ISSUE TITLE
Small video size

### ISSUE THREAD

**Issue by mll** [AdColony/AdColony-iOS-SDK-3#44]
Sometimes the ad plays inside a tiny section of the screen. The rest of the screen is black.

**Comment by gswati8** [comment]
Sorry to know that you are facing issues. Please share the entire console log and Charles logs for our team to review further.Also, can you please confirm which version of SDK are you using and if it is a direct integration or you are using a mediation partner. Please send this to support@adcolony.com for streamlined communication.
