### ISSUE TITLE
Crash on v.3.2.1, AdColony setupWorkerThread -> JavaScriptCore

### ISSUE THREAD

**Issue by lyodev** [AdColony/AdColony-iOS-SDK-3#45]
0 | JavaScriptCore 0x000000018db3cfd4 sanitizeStackForVMImpl + 16
  | 1 | JavaScriptCore 0x000000018d9802e0 JSC::Heap::runCurrentPhase() + 80
  | 2 | JavaScriptCore 0x000000018d9833e8 JSC::Heap::collectInMutatorThread() + 44
  | 3 | JavaScriptCore 0x000000018d9832cc JSC::Heap::stopIfNecessarySlow() + 60
  | 4 | JavaScriptCore 0x000000018d983568 JSC::Heap::acquireAccessSlow() + 312
  | 5 | JavaScriptCore 0x000000018da92c60 JSC::JSLock::didAcquireLock() + 124
  | 6 | JavaScriptCore 0x000000018dab3ac4 JSC::JSRunLoopTimer::timerDidFire() + 24
  | 7 | CoreFoundation 0x0000000186a8292c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 24
  | 8 | CoreFoundation 0x0000000186a82650 __CFRunLoopDoTimer + 860
  | 9 | CoreFoundation 0x0000000186a81e50 __CFRunLoopDoTimers + 244
  | 10 | CoreFoundation 0x0000000186a7fa38 __CFRunLoopRun + 1924
  | 11 | CoreFoundation 0x000000018699ffb8 CFRunLoopRunSpecific + 432
  | 12 | Foundation 0x00000001873c96e4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
! | 13 | deerhunt16 0x00000001023da420 -[AdColony setupWorkerThread] (AdColony.m:156)
  | 14 | Foundation 0x00000001874ca860 __NSThread__start__ + 992
  | 15 | libsystem_pthread.dylib 0x000000018670431c _pthread_body + 304
  | 16 | libsystem_pthread.dylib 0x00000001867041e8 _pthread_start + 308
  | 17 | libsystem_pthread.dylib 0x0000000186702c28 thread_start + 0

**Comment by gswati8** [comment]
To look into this further, please share the entire console log and Charles logs for our team to review.Also, can you please confirm which version of SDK are you using. Please send this to support@adcolony.com for streamlined communication.

**Comment by lyodev** [comment]
It was reported on Crittercism. There is no entire console log or Charles log.
