### ISSUE TITLE
"Xcode-Project-Setup" maybe wrong?

### ISSUE THREAD

**Issue by jus18tin** [AdColony/AdColony-iOS-SDK-3#46]
https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup#linking-the-required-dependencies
### now
- EventKit.framework (Set to Optional)
- JavaScriptCore.framework

### Isn't it should be 
- EventKit.framework
- JavaScriptCore.framework (Set to Optional)

As `JavaScriptCore.framework` is available from iOS 7

**Comment by gswati8** [comment]
Thanks for bringing this to our attention. The screenshot shows JavaScriptCore.framework (Set to Optional) while in the docs it is mentioned as Required. We will fix it. 

JavaScriptCore.framework is a required framework as it's a fundamental requirement by the SDK. 
EventKit.framework is optional as it's needed to show ads that access calendar events. Some application developers do not wish to enable calendar permissions, thus ads requiring calendar access are not served, and hence EventKit is not needed in these cases. Thus, Event kit is set to optional.
