### ISSUE TITLE
Orientation problem in ios

### ISSUE THREAD

**Issue by imobdevtech** [AdColony/AdColony-iOS-SDK-3#47]
I have portrait mode application and now i need to integrate adcolony in my project but document state that adcolony video also in landscape mode so how i can handle this things in my project.

**Comment by cmanibog-ac** [comment]
You can force ads to be served in portrait orientation in AdColonyAppOptions. Our API details on this can be seen at https://adcolony-www-common.s3.amazonaws.com/Appledoc/3.3.0/Classes/AdColonyAppOptions.html#//api/name/adOrientation.

Additionally, an AdColony admin can override the ad viewing orientation in a setting in our dashboard. If you could let us know your AdColony app ID, we can update your app. Feel free to share this information with our Support team at support@adcolony.com.

**Comment by imobdevtech** [comment]
@cmanibog-ac  we set orientation in AdColonyAppOptions but still i got the landscape video. here is  my code.

```
let adColonyAppOption = AdColonyAppOptions.init()
            if let userData = getUserDataFromFile()
            {
                adColonyAppOption.userID = userData.userID
            }
            adColonyAppOption.adOrientation = .portrait
            AdColony.configure(withAppID: read_Localizable("adColonyKey"), zoneIDs: [read_Localizable("ZoneIDs")], options: nil,completion:{(zones) in
            })
```

**Comment by cmanibog-ac** [comment]
Everything looks fine except for the value that is being passed. Instead of passing .portrait, could you send it as AdColonyOrientationPortrait, like mentioned here https://adcolony-www-common.s3.amazonaws.com/Appledoc/3.3.0/Constants/AdColonyOrientation.html?
