### ISSUE TITLE
Blank screen when you click on the Ad CTA button & scroll down on the In-App Appstore view.

### ISSUE THREAD

**Issue by sanju-naik** [AdColony/AdColony-iOS-SDK-3#48]
Hi,

We have upgraded from 3.2.1 to 3.3.0 and we are experiencing this blank screen issue on your latest SDK version. 

Steps to reproduce : 
- Click on Video ad CTA Button.
- It opens up a In-App Appstore view to install the ad, scroll down on that page.
- After scrolling a bit it show empty white screen & you are stuck there, The only way to exit this screen is force quit your app.

Can you please look into this issue ?

**Comment by cmanibog-ac** [comment]
@sanju-naik I'll see if our Engineering team is able to reproduce this issue. In the meantime, could you share a video of this behavior and a console log showing the app activity from when our SDK is initialized through the white screen issue?

Also feel free to share this and future requests through our support channel at support@adcolony.com for streamlined communication with our Support/Engineering teams.
