### ISSUE TITLE
crash after dismissing a reward video

### ISSUE THREAD

**Issue by aporat** [AdColony/AdColony-iOS-SDK-3#5]
crash after dismissing a reward video on ios 10.1, iphone 7. my app does not support landscape mode

`*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ADCContainer shouldAutorotate] is returning YES'`

using latest 3.0.4.1 SDK

**Comment by qichuan** [comment]
It happens to my app as well. AdColony team can you please take a look?

**Comment by mwhite-ac** [comment]
We have tested a fix for this but don't have it available in the public repository yet. Please send an email to support@adcolony.com and we'll provide you a link to get this update. Note that this update is fully tested and not a beta version of the fix.

**Comment by owainm** [comment]
Fix is available in v3.0.6

**Comment by victorfigol** [comment]
3.0.6 still crashes

**Comment by arun-perk** [comment]
@victorfigol  3.0.6 works for me. You just need to force orientation to landscape while adcolony being displayed.

**Comment by coolcool1994** [comment]
sharedControl is undefined? Can you provide us with the full the full code?
