### ISSUE TITLE
Audio session killed upon initialization

### ISSUE THREAD

**Issue by finngaida** [AdColony/AdColony-iOS-SDK-3#50]
The app I'm working on calls `[AdColony configureWithAppID:...]` during `application:didFinishLaunchingWithOptions` and apparently this call cuts all external audio.

Meaning if a user has Music playing from Apple Music or Spotify or is listening to any other form of background audio this will get stopped and can only be resumed from the app that it was originally started from. That is extremely bad UX.
I assume at some point an `AVAudioSession` is set active, although it's not yet necessary, since no ads are shown yet.

Are there any options I can pass in order to stop this behavior? If not is there any way I can otherwise change the code to do so? I don't want to drop AdColony, but this behavior is also not acceptable.

**Comment by finngaida** [comment]
Is anyone reading this?

**Comment by lupatus** [comment]
Yeah, sorry for late reply, let me check that.

**Comment by lupatus** [comment]
This issue is addressed and will be fixed with version 3.3.6 - should be released pretty soon, we're validating it at the moment.

**Comment by finngaida** [comment]
Great! Thanks for taking the time to look into it!

**Comment by superjd** [comment]
@finngaida did you integrate 3.3.6? and is your issue resolved?

**Comment by finngaida** [comment]
Oh yes the new update fixed it

**Comment by thithuhanguyen** [comment]
Let me check
