### ISSUE TITLE
Ads do not serve

### ISSUE THREAD

**Issue by grantpowell** [AdColony/AdColony-iOS-SDK-3#52]
Ads are not serving. SDK does not work. We have been unable to reach anyone on your team.

**Comment by mwhite-ac** [comment]
@grantpowell Our Marketing team passed your contact to our Support team a bit earlier today and I have your information in our queue.  But, we'll need more information to dig into this further, you can speed troubleshooting by sending an email to support@adcolony.com including your AdColony app ID, version of the SDK you're working with and a full console log showing all app activity from when you initialize our SDK through an attempted video play.
