### ISSUE TITLE
NSRangeException in [ADCWebViewAPI prepare:]

### ISSUE THREAD

**Issue by opendoorapp** [AdColony/AdColony-iOS-SDK-3#6]
Crashes randomly with the following stack trace

Fatal Exception: NSRangeException
0  CoreFoundation                 0x1942f01c0 **exceptionPreprocess
1  libobjc.A.dylib                0x192d2855c objc_exception_throw
2  CoreFoundation                 0x1942f0108 -[NSException initWithCoder:]
3  Foundation                     0x194cf96d4 -[NSString substringFromIndex:]
4  XXXXXXX                       0x1001bf0a0 -[ADCWebViewAPI prepare:](ADCWebViewAPI.m:247)
5  XXXXXXX                       0x1001e3ef4 -[ADCNativeLayer dispatchMessage:](ADCNativeLayer.m:253)
6  XXXXXXX                       0x1001e3b70 __24-[ADCNativeLayer update]_block_invoke (ADCNativeLayer.m:190)
7  XXXXXXX                       0x1001b9e54 -[ADCJSCoreModule pumpMessages:](ADCJSCoreModule.m:166)
8  XXXXXXX                       0x1001e383c -[ADCNativeLayer update](ADCNativeLayer.m:192)
9  Foundation                     0x194dd7988 __NSFireTimer
10 CoreFoundation                 0x19429e8f4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION**
11 CoreFoundation                 0x19429e608 **CFRunLoopDoTimer
12 CoreFoundation                 0x19429dec4 __CFRunLoopDoTimers
13 CoreFoundation                 0x19429bac0 __CFRunLoopRun
14 CoreFoundation                 0x1941ca048 CFRunLoopRunSpecific
15 Foundation                     0x194cd8b1c -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
16 XXXXXXX                       0x100231990 -[AdColony setupWorkerThread](AdColony.m:117)
17 Foundation                     0x194dd650c __NSThread__start**
18 libsystem_pthread.dylib        0x193383860 _pthread_body
19 libsystem_pthread.dylib        0x193383770 _pthread_body
20 libsystem_pthread.dylib        0x193380dbc thread_start

**Comment by owainm** [comment]
Fix is available in v3.0.6
